# Action Plan Measures feature (2026-07-27): any performance_measure
# marked Citywide (is_city = TRUE) now surfaces in a dedicated admin list
# page and in its pillar's modal, replacing reference.action_plan_measure
# (dropped -- it held dummy data generated by another bot, not real
# measures). See data$city_measures / data$strategic_plan's metrics
# construction in R/database.R, and metric_visual()/
# action_plan_measure_item() in app.R.

test_that("metric_visual renders without error when a measure has no data yet", {
  # Regression guard: max(NA, NA, na.rm = TRUE) is -Inf with a warning,
  # which broke rendering entirely for a Citywide measure with neither an
  # actual nor a target recorded for the current snapshot years.
  metric <- list(name = "No data measure", current = NA_real_, target = NA_real_, direction = "Increase", unit = NULL, format_type = "Count")
  html <- as.character(metric_visual(metric))
  expect_true(grepl("No data measure", html))
  expect_false(grepl("-Inf", html))
})

test_that("metric_visual formats labels using format_type, not a raw number", {
  # Regression guard: metric$unit is NULL (not NA) when absent, but
  # format_measure_value() checks is.na(display_unit) -- is.na(NULL) is
  # logical(0), which throws inside an `if`. Also confirms Percent values
  # (stored as fractions) render as a percentage, not the raw fraction.
  metric <- list(name = "Percent measure", current = 0.74, target = 0.85, direction = "Increase", unit = NULL, format_type = "Percent")
  html <- as.character(metric_visual(metric))
  expect_true(grepl("74%", html))
  expect_true(grepl("85%", html))
})

test_that("metric_visual handles only one of current/target being set", {
  metric <- list(name = "Target only", current = NA_real_, target = 500, direction = "Increase", unit = NULL, format_type = "Currency")
  html <- as.character(metric_visual(metric))
  expect_true(grepl("\\$500", html))
  expect_true(grepl("Not set", html))
})

test_that("action_plan_measure_item shows a placeholder, not a chart, when a measure has no data at all", {
  metric <- list(name = "Brand new Citywide measure", current = NA_real_, target = NA_real_, direction = "Increase", unit = NULL, format_type = "Count")
  html <- as.character(action_plan_measure_item(metric))
  expect_true(grepl("Awaiting data", html))
  expect_false(grepl("metric-viz", html))
})

test_that("action_plan_measure_item shows the chart once at least one value is recorded", {
  metric <- list(name = "Has an actual", current = 42, target = NA_real_, direction = "Increase", unit = NULL, format_type = "Count")
  html <- as.character(action_plan_measure_item(metric))
  expect_true(grepl("metric-viz", html))
  expect_false(grepl("Awaiting data", html))
})

test_that("data$city_measures surfaces a Citywide measure with its agency/pillar joined and the right snapshot years", {
  skip_if_no_test_database()
  connection <- connect_app_database()

  agency_id <- DBI::dbGetQuery(connection, "SELECT agency_id FROM reference.agency LIMIT 1")$agency_id[[1]]
  cycle_id <- DBI::dbGetQuery(connection, "SELECT cycle_id FROM planning.plan_cycle LIMIT 1")$cycle_id[[1]]
  user_id <- DBI::dbGetQuery(connection, 'SELECT user_id FROM access."user" LIMIT 1')$user_id[[1]]
  pillar_id <- DBI::dbGetQuery(connection, "SELECT pillar_id FROM reference.pillar LIMIT 1")$pillar_id[[1]]
  fy <- current_fiscal_year()

  values <- list(
    measure_id = NULL, agency_id = agency_id, initial_cycle = cycle_id,
    title = "Action Plan Measures test fixture", measure_type = "Output", description = "d",
    data_source = "s", data_owner = "o", data_owner_role = "r", update_frequency = "Monthly",
    formula = "f", desired_direction = "Increase", baseline_value = 10, baseline_fy = fy - 4L,
    format_type = "Count", display_unit = NA_character_, context_required = "", replicability = TRUE,
    disaggregation = "", data_location = "", collection_method = "", how_data_used = "",
    why_meaningful = "", proxy_measure = "", improvement_notes = "", change_mapping = "New",
    pillar_id = pillar_id, pillar_goal_id = NA_integer_, is_city = TRUE, is_agency = FALSE, is_service = TRUE,
    approval_status = "Draft", submitted_for_approval_at = as.POSIXct(NA)
  )
  # Actual and target land in different fiscal years on purpose, to
  # exercise city_measures' two separate LEFT JOINs independently (last
  # complete year's actual, current year's target) rather than leaving it
  # ambiguous which join produced which value.
  yearly_values <- list(
    list(fiscal_year = fy - 1L, annual_actual = 100, annual_actual_notes = "", target_value = NA_real_, target_value_notes = ""),
    list(fiscal_year = fy, annual_actual = NA_real_, annual_actual_notes = "", target_value = 90, target_value_notes = "")
  )
  measure_id <- save_measure_record(connection, values, yearly_values, user_id, submit = FALSE, is_admin = TRUE)
  on.exit(
    {
      DBI::dbExecute(connection, "DELETE FROM performance.measure_actuals WHERE measure_id = $1", params = list(measure_id))
      DBI::dbExecute(connection, "DELETE FROM performance.performance_measure WHERE measure_id = $1", params = list(measure_id))
      DBI::dbDisconnect(connection)
    },
    add = TRUE
  )

  db <- load_app_data(connection)
  row <- db$city_measures[db$city_measures$measure_id == measure_id, , drop = FALSE]
  expect_equal(nrow(row), 1L)
  expect_equal(row$agency_id[[1]], agency_id)
  expect_equal(row$pillar_id[[1]], pillar_id)
  expect_equal(row$current_value[[1]], 100)
  expect_equal(row$target_value[[1]], 90)

  pillar_entry <- Filter(function(p) p$id == pillar_id, db$strategic_plan)[[1]]
  metric <- Filter(function(m) m$measure_id == measure_id, pillar_entry$metrics)[[1]]
  expect_equal(metric$name, "Action Plan Measures test fixture")
  expect_equal(metric$target, 90)
})

test_that("a measure marked Citywide without a pillar still appears in city_measures but not in any pillar's metrics", {
  skip_if_no_test_database()
  connection <- connect_app_database()

  agency_id <- DBI::dbGetQuery(connection, "SELECT agency_id FROM reference.agency LIMIT 1")$agency_id[[1]]
  cycle_id <- DBI::dbGetQuery(connection, "SELECT cycle_id FROM planning.plan_cycle LIMIT 1")$cycle_id[[1]]
  user_id <- DBI::dbGetQuery(connection, 'SELECT user_id FROM access."user" LIMIT 1')$user_id[[1]]
  fy <- current_fiscal_year()

  values <- list(
    measure_id = NULL, agency_id = agency_id, initial_cycle = cycle_id,
    title = "Unlinked Citywide test fixture", measure_type = "Output", description = "d",
    data_source = "s", data_owner = "o", data_owner_role = "r", update_frequency = "Monthly",
    formula = "f", desired_direction = "Increase", baseline_value = 10, baseline_fy = fy - 4L,
    format_type = "Count", display_unit = NA_character_, context_required = "", replicability = TRUE,
    disaggregation = "", data_location = "", collection_method = "", how_data_used = "",
    why_meaningful = "", proxy_measure = "", improvement_notes = "", change_mapping = "New",
    pillar_id = NA_integer_, pillar_goal_id = NA_integer_, is_city = TRUE, is_agency = FALSE, is_service = TRUE,
    approval_status = "Draft", submitted_for_approval_at = as.POSIXct(NA)
  )
  measure_id <- save_measure_record(connection, values, list(), user_id, submit = FALSE, is_admin = TRUE)
  on.exit(
    {
      DBI::dbExecute(connection, "DELETE FROM performance.performance_measure WHERE measure_id = $1", params = list(measure_id))
      DBI::dbDisconnect(connection)
    },
    add = TRUE
  )

  db <- load_app_data(connection)
  row <- db$city_measures[db$city_measures$measure_id == measure_id, , drop = FALSE]
  expect_equal(nrow(row), 1L)
  expect_true(is.na(row$pillar_id[[1]]))

  all_metric_ids <- unlist(lapply(db$strategic_plan, function(p) vapply(p$metrics, function(m) m$measure_id, integer(1))))
  expect_false(measure_id %in% all_metric_ids)
})
