source("R/database.R")

csv_dir <- "outputs/performance_entity_table"
link_path <- file.path(csv_dir, "measure_entity_link_load.csv")
measure_path <- file.path(csv_dir, "missing_measure_load.csv")
actual_path <- file.path(csv_dir, "missing_measure_actuals_load.csv")

required_files <- c(link_path, measure_path, actual_path)
missing_files <- required_files[!file.exists(required_files)]
if (length(missing_files)) {
  stop("Missing load file(s): ", paste(missing_files, collapse = ", "))
}

con <- connect_app_database()
on.exit(DBI::dbDisconnect(con), add = TRUE)

DBI::dbExecute(con, "
CREATE TABLE IF NOT EXISTS performance.measure_entity_link (
    link_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    measure_id integer NOT NULL REFERENCES performance.performance_measure(measure_id),
    agency_id varchar(20) NOT NULL REFERENCES reference.agency(agency_id),
    service_id varchar(20) NOT NULL REFERENCES reference.service(service_id),
    entity_type varchar(30) NOT NULL CHECK (entity_type IN ('service', 'mayoral service', 'quasi agency')),
    entity_id integer REFERENCES reference.plan_entity(entity_id),
    public_name varchar(300) NOT NULL,
    source_old_measure_id varchar(50),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK (
        (entity_type = 'service' AND entity_id IS NULL)
        OR (entity_type IN ('mayoral service', 'quasi agency') AND entity_id IS NOT NULL)
    ),
    UNIQUE (measure_id, agency_id, service_id, entity_type, entity_id)
)")
DBI::dbExecute(con, "CREATE INDEX IF NOT EXISTS idx_measure_entity_link_measure_id ON performance.measure_entity_link(measure_id)")
DBI::dbExecute(con, "CREATE INDEX IF NOT EXISTS idx_measure_entity_link_agency_id ON performance.measure_entity_link(agency_id)")
DBI::dbExecute(con, "CREATE INDEX IF NOT EXISTS idx_measure_entity_link_service_id ON performance.measure_entity_link(service_id)")
DBI::dbExecute(con, "CREATE INDEX IF NOT EXISTS idx_measure_entity_link_entity_id ON performance.measure_entity_link(entity_id)")

links <- read.csv(link_path, stringsAsFactors = FALSE, na.strings = c(""))
measures <- read.csv(measure_path, stringsAsFactors = FALSE, na.strings = c(""))
actuals <- read.csv(actual_path, stringsAsFactors = FALSE, na.strings = c(""))

cycle <- DBI::dbGetQuery(con, "SELECT cycle_id FROM planning.plan_cycle WHERE fiscal_year = 2027")
if (!nrow(cycle)) stop("FY2027 plan cycle is missing")
cycle_id <- cycle$cycle_id[[1]]

DBI::dbWithTransaction(con, {
  if (nrow(measures)) {
    for (i in seq_len(nrow(measures))) {
      row <- measures[i, , drop = FALSE]
      DBI::dbExecute(
        con,
        paste(
          "INSERT INTO performance.performance_measure",
          "(measure_id, agency_id, initial_cycle, title, measure_type, description, data_source, data_owner, data_owner_role, update_frequency, formula, desired_direction, format_type, change_mapping, is_service, active, validated, approval_status)",
          "VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,true,$15,$16,$17)",
          "ON CONFLICT (measure_id) DO UPDATE SET",
          "agency_id = EXCLUDED.agency_id, initial_cycle = EXCLUDED.initial_cycle, title = EXCLUDED.title, measure_type = EXCLUDED.measure_type,",
          "description = EXCLUDED.description, data_source = EXCLUDED.data_source, data_owner = EXCLUDED.data_owner, data_owner_role = EXCLUDED.data_owner_role,",
          "update_frequency = EXCLUDED.update_frequency, formula = EXCLUDED.formula, desired_direction = EXCLUDED.desired_direction, format_type = EXCLUDED.format_type,",
          "change_mapping = EXCLUDED.change_mapping, is_service = true, active = EXCLUDED.active, validated = EXCLUDED.validated, approval_status = EXCLUDED.approval_status, last_updated = now()"
        ),
        params = list(
          as.integer(row$measure_id), row$agency_id, cycle_id, row$title, row$measure_type, row$description,
          row$data_source, row$data_owner, row$data_owner_role, row$update_frequency, row$formula,
          row$desired_direction, row$format_type, row$change_mapping, as.logical(row$active),
          as.logical(row$validated), row$approval_status
        )
      )
    }
  }

  if (nrow(actuals)) {
    for (i in seq_len(nrow(actuals))) {
      row <- actuals[i, , drop = FALSE]
      DBI::dbExecute(
        con,
        paste(
          "INSERT INTO performance.measure_actuals",
          "(measure_id, fiscal_year, annual_actual, annual_actual_notes, target_value, target_value_notes, reported_by)",
          "VALUES ($1,$2,$3,$4,$5,$6,2)",
          "ON CONFLICT (measure_id, fiscal_year) DO UPDATE SET",
          "annual_actual = EXCLUDED.annual_actual, annual_actual_notes = EXCLUDED.annual_actual_notes,",
          "target_value = EXCLUDED.target_value, target_value_notes = EXCLUDED.target_value_notes, updated_at = now()"
        ),
        params = list(
          as.integer(row$measure_id), as.integer(row$fiscal_year), row$annual_actual,
          row$annual_actual_notes, row$target_value, row$target_value_notes
        )
      )
    }
  }

  DBI::dbExecute(con, "TRUNCATE performance.measure_entity_link RESTART IDENTITY")
  for (i in seq_len(nrow(links))) {
    row <- links[i, , drop = FALSE]
    DBI::dbExecute(
      con,
      paste(
        "INSERT INTO performance.measure_entity_link",
        "(measure_id, agency_id, service_id, entity_type, entity_id, public_name, source_old_measure_id)",
        "VALUES ($1,$2,$3,$4,$5,$6,$7)"
      ),
      params = list(
        as.integer(row$measure_id),
        row$agency_id,
        row$service_id,
        row$entity_type,
        if (is.na(row$entity_id) || !nzchar(row$entity_id)) NA_integer_ else as.integer(row$entity_id),
        row$public_name,
        row$source_old_measure_id
      )
    )
  }

  entity_service_rows <- unique(links[links$entity_type %in% c("mayoral service", "quasi agency"), c("entity_id", "service_id")])
  entity_service_rows <- entity_service_rows[!is.na(entity_service_rows$entity_id) & nzchar(entity_service_rows$entity_id), , drop = FALSE]
  if (nrow(entity_service_rows)) {
    for (i in seq_len(nrow(entity_service_rows))) {
      row <- entity_service_rows[i, , drop = FALSE]
      DBI::dbExecute(
        con,
        paste(
          "INSERT INTO reference.plan_entity_service (entity_id, service_id, is_primary)",
          "VALUES ($1,$2,false)",
          "ON CONFLICT (entity_id, service_id) DO NOTHING"
        ),
        params = list(as.integer(row$entity_id), row$service_id)
      )
    }
  }

  plan_services <- DBI::dbGetQuery(
    con,
    paste(
      "SELECT ap.plan_id, pes.service_id",
      "FROM planning.agency_plan ap",
      "JOIN reference.plan_entity_service pes ON pes.entity_id = ap.entity_id",
      "WHERE ap.cycle_id = $1"
    ),
    params = list(cycle_id)
  )
  if (nrow(plan_services)) {
    for (i in seq_len(nrow(plan_services))) {
      row <- plan_services[i, , drop = FALSE]
      next_order <- DBI::dbGetQuery(
        con,
        "SELECT COALESCE(MAX(sort_order), 0) + 1 AS sort_order FROM performance.plan_service WHERE plan_id = $1",
        params = list(row$plan_id)
      )$sort_order[[1]]
      DBI::dbExecute(
        con,
        paste(
          "INSERT INTO performance.plan_service (plan_id, service_id, sort_order)",
          "VALUES ($1,$2,$3)",
          "ON CONFLICT (plan_id, service_id) DO NOTHING"
        ),
        params = list(row$plan_id, row$service_id, next_order)
      )
    }
  }

  DBI::dbExecute(
    con,
    paste(
      "INSERT INTO performance.pm_service_link (measure_id, service_id)",
      "SELECT DISTINCT measure_id, service_id FROM performance.measure_entity_link",
      "ON CONFLICT (measure_id, service_id) DO NOTHING"
    )
  )
})

summary <- DBI::dbGetQuery(con, "
SELECT
  COUNT(*) AS entity_links,
  COUNT(*) FILTER (WHERE entity_type = 'service') AS service_links,
  COUNT(*) FILTER (WHERE entity_type = 'mayoral service') AS mayoral_service_links,
  COUNT(*) FILTER (WHERE entity_type = 'quasi agency') AS quasi_agency_links
FROM performance.measure_entity_link
")
print(summary)
