source(file.path("R", "database.R"))

con <- connect_app_database()
on.exit(DBI::dbDisconnect(con), add = TRUE)

DBI::dbWithTransaction(con, {
  DBI::dbExecute(con, "ALTER TABLE performance.performance_measure DROP CONSTRAINT IF EXISTS performance_measure_approval_status_check")
  DBI::dbExecute(
    con,
    "ALTER TABLE performance.performance_measure
     ADD CONSTRAINT performance_measure_approval_status_check
     CHECK (approval_status IN ('Draft', 'PendingApproval', 'Validated', 'Returned', 'Rejected'))"
  )
  DBI::dbExecute(
    con,
    "CREATE TABLE IF NOT EXISTS review.measure_review (
      measure_review_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      measure_id integer NOT NULL REFERENCES performance.performance_measure(measure_id),
      reviewer_id integer REFERENCES access.\"user\"(user_id),
      decision varchar(20) NOT NULL CHECK (decision IN ('Approved', 'Returned')),
      feedback text,
      reviewed_at timestamptz NOT NULL DEFAULT now(),
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now(),
      modified_by integer REFERENCES access.\"user\"(user_id)
    )"
  )
  DBI::dbExecute(con, "CREATE INDEX IF NOT EXISTS idx_measure_review_measure_id ON review.measure_review(measure_id)")
  DBI::dbExecute(con, "CREATE INDEX IF NOT EXISTS idx_measure_review_reviewer_id ON review.measure_review(reviewer_id)")
})

message("Measure review schema ready.")
