-- Target Postgres schema for the Agency Performance & Budget Portal.
-- Adapted from Target_Database_Schema.pdf (Azure SQL, May 2026).
-- This file creates the durable app schema. Dummy data should be loaded separately.

BEGIN;

CREATE SCHEMA IF NOT EXISTS reference;
CREATE SCHEMA IF NOT EXISTS access;
CREATE SCHEMA IF NOT EXISTS planning;
CREATE SCHEMA IF NOT EXISTS performance;
CREATE SCHEMA IF NOT EXISTS budget;
CREATE SCHEMA IF NOT EXISTS review;
CREATE SCHEMA IF NOT EXISTS workflow;
CREATE SCHEMA IF NOT EXISTS amendment;
CREATE SCHEMA IF NOT EXISTS output;

CREATE TABLE IF NOT EXISTS reference.pillar (
    pillar_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pillar_name varchar(200) NOT NULL,
    pillar_lead varchar(200),
    sort_order integer NOT NULL CHECK (sort_order BETWEEN 1 AND 6),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS reference.pillar_goal (
    pillar_goal_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pillar_id integer NOT NULL REFERENCES reference.pillar(pillar_id),
    goal_code varchar(10) NOT NULL UNIQUE,
    goal_title varchar(500) NOT NULL,
    goal_lead varchar(200),
    sort_order integer NOT NULL
);

CREATE TABLE IF NOT EXISTS reference.agency (
    agency_id varchar(20) PRIMARY KEY,
    agency_name varchar(200) NOT NULL,
    public_name varchar(300),
    deputy_mayor_pillar varchar(100),
    is_quasi boolean NOT NULL DEFAULT false,
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS reference.service (
    service_id varchar(20) PRIMARY KEY,
    service_name varchar(300) NOT NULL,
    agency_id varchar(20) NOT NULL REFERENCES reference.agency(agency_id),
    service_type varchar(20) NOT NULL CHECK (service_type IN ('Performance', 'Administrative')),
    service_description text,
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS reference.cost_center (
    cost_center_id varchar(20) PRIMARY KEY,
    cost_center_name varchar(300) NOT NULL,
    service_id varchar(20) NOT NULL REFERENCES reference.service(service_id),
    agency_id varchar(20) NOT NULL REFERENCES reference.agency(agency_id),
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS reference.plan_entity (
    entity_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_agency_id varchar(20) NOT NULL REFERENCES reference.agency(agency_id),
    public_name varchar(300) NOT NULL,
    entity_type varchar(30) NOT NULL CHECK (entity_type IN ('MayoraltyOffice', 'QuasiAgency', 'Other')),
    has_own_plan boolean NOT NULL DEFAULT true,
    active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS reference.plan_entity_service (
    pes_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id integer NOT NULL REFERENCES reference.plan_entity(entity_id),
    service_id varchar(20) NOT NULL REFERENCES reference.service(service_id),
    is_primary boolean NOT NULL DEFAULT false,
    UNIQUE (entity_id, service_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_plan_entity_service_primary
    ON reference.plan_entity_service(entity_id)
    WHERE is_primary;

CREATE TABLE IF NOT EXISTS access."user" (
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(300) NOT NULL UNIQUE,
    full_name varchar(200) NOT NULL,
    phone varchar(30),
    auth_type varchar(20) NOT NULL CHECK (auth_type IN ('Email', 'MicrosoftAD')),
    password_hash varchar(500),
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS access.user_role (
    user_role_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES access."user"(user_id),
    app_role varchar(30) NOT NULL CHECK (app_role IN (
        'AgencySubmitter', 'AgencyApprover', 'OPIReviewer', 'BBMRReviewer',
        'DeputyMayor', 'CAOffice', 'SystemAdmin', 'AgencyViewer'
    )),
    agency_id varchar(20) REFERENCES reference.agency(agency_id),
    pillar_id integer REFERENCES reference.pillar(pillar_id),
    granted_at timestamptz NOT NULL DEFAULT now(),
    budget_access boolean NOT NULL DEFAULT false,
    adaptive_planning boolean NOT NULL DEFAULT false,
    performance_plan_access boolean NOT NULL DEFAULT false,
    quasi boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS access.user_agency_access (
    access_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES access."user"(user_id),
    agency_id varchar(20) NOT NULL REFERENCES reference.agency(agency_id),
    service_id varchar(20) REFERENCES reference.service(service_id),
    agency_role varchar(30) NOT NULL CHECK (agency_role IN (
        'Agency Head', 'Agency Director', 'Chief of Staff', 'Fiscal Officer',
        'Agency Staff', 'Performance Lead', 'Admin'
    )),
    UNIQUE (user_id, agency_id, service_id)
);

CREATE TABLE IF NOT EXISTS planning.plan_cycle (
    cycle_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiscal_year integer NOT NULL UNIQUE,
    summer_open date NOT NULL,
    summer_close date NOT NULL,
    fall_open date,
    fall_close date,
    cycle_status varchar(20) NOT NULL CHECK (cycle_status IN (
        'Upcoming', 'SummerOpen', 'SummerClosed', 'FallOpen', 'FallClosed', 'Complete'
    )),
    created_by integer NOT NULL REFERENCES access."user"(user_id),
    CHECK (summer_close >= summer_open),
    CHECK (fall_close IS NULL OR fall_open IS NULL OR fall_close >= fall_open)
);

CREATE TABLE IF NOT EXISTS planning.agency_plan (
    plan_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id varchar(20) REFERENCES reference.agency(agency_id),
    entity_id integer REFERENCES reference.plan_entity(entity_id),
    cycle_id integer NOT NULL REFERENCES planning.plan_cycle(cycle_id),
    plan_status varchar(30) NOT NULL CHECK (plan_status IN (
        'Draft', 'Submitted', 'UnderReview', 'FeedbackReturned', 'AgencyRevised',
        'DirectorSignOff', 'DeputyMayorReview', 'CAReview', 'Approved', 'Amended'
    )),
    budget_status varchar(30) NOT NULL CHECK (budget_status IN (
        'Locked', 'Draft', 'Submitted', 'UnderReview', 'FeedbackReturned', 'Approved'
    )),
    version integer NOT NULL DEFAULT 1 CHECK (version >= 1),
    assigned_reviewer integer REFERENCES access."user"(user_id),
    submitted_at timestamptz,
    approved_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((agency_id IS NOT NULL)::integer + (entity_id IS NOT NULL)::integer = 1),
    UNIQUE (agency_id, cycle_id),
    UNIQUE (entity_id, cycle_id)
);

CREATE TABLE IF NOT EXISTS performance.plan_header (
    header_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id integer NOT NULL UNIQUE REFERENCES planning.agency_plan(plan_id),
    primary_contact_name varchar(200) NOT NULL,
    primary_contact_email varchar(300) NOT NULL,
    plan_date date NOT NULL,
    version_label varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS performance.mission_vision (
    mv_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id integer NOT NULL UNIQUE REFERENCES planning.agency_plan(plan_id),
    mission text NOT NULL,
    vision text NOT NULL
);

CREATE TABLE IF NOT EXISTS performance.plan_pillar_alignment (
    alignment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id integer NOT NULL REFERENCES planning.agency_plan(plan_id),
    pillar_id integer NOT NULL REFERENCES reference.pillar(pillar_id),
    UNIQUE (plan_id, pillar_id)
);

CREATE TABLE IF NOT EXISTS performance.agency_goal (
    agency_goal_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id integer NOT NULL REFERENCES planning.agency_plan(plan_id),
    title varchar(500) NOT NULL,
    description text,
    sort_order integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (plan_id, sort_order)
);

CREATE TABLE IF NOT EXISTS performance.agency_goal_pillar_link (
    link_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_goal_id integer NOT NULL REFERENCES performance.agency_goal(agency_goal_id),
    pillar_goal_id integer NOT NULL REFERENCES reference.pillar_goal(pillar_goal_id),
    link_type varchar(20) NOT NULL CHECK (link_type IN ('Primary', 'Secondary')),
    alignment_narrative text,
    created_date date NOT NULL DEFAULT current_date,
    UNIQUE (agency_goal_id, pillar_goal_id)
);

CREATE TABLE IF NOT EXISTS performance.initiative (
    initiative_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(500) NOT NULL,
    description text,
    start_date date,
    end_date date,
    status varchar(30) NOT NULL CHECK (status IN ('Planned', 'InProgress', 'Completed', 'OnHold')),
    created_date date NOT NULL DEFAULT current_date,
    last_updated timestamptz NOT NULL DEFAULT now(),
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS performance.agency_goal_initiative_link (
    link_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_goal_id integer NOT NULL REFERENCES performance.agency_goal(agency_goal_id),
    initiative_id integer NOT NULL REFERENCES performance.initiative(initiative_id),
    link_type varchar(20) NOT NULL CHECK (link_type IN ('Primary', 'Secondary')),
    created_date date NOT NULL DEFAULT current_date,
    UNIQUE (agency_goal_id, initiative_id)
);

CREATE TABLE IF NOT EXISTS performance.performance_measure (
    measure_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id varchar(20) NOT NULL REFERENCES reference.agency(agency_id),
    initial_cycle integer NOT NULL REFERENCES planning.plan_cycle(cycle_id),
    title varchar(500) NOT NULL,
    is_kpi boolean NOT NULL DEFAULT false,
    measure_type varchar(30) NOT NULL CHECK (measure_type IN ('Output', 'Efficiency', 'Effectiveness', 'Outcome')),
    description text NOT NULL,
    data_source varchar(500) NOT NULL,
    data_owner varchar(200) NOT NULL,
    data_owner_role varchar(200) NOT NULL,
    update_frequency varchar(50) NOT NULL,
    formula text NOT NULL,
    desired_direction varchar(20) NOT NULL CHECK (desired_direction IN ('Increase', 'Decrease', 'Maintain')),
    baseline_value numeric(18,4),
    baseline_fy integer,
    format_type varchar(20) NOT NULL CHECK (format_type IN ('Percent', 'Count', 'Currency', 'Rate', 'Decimal', 'Days', 'Score')),
    display_unit varchar(100),
    context_required text,
    replicability boolean,
    disaggregation text,
    data_location varchar(500),
    collection_method text,
    how_data_used text,
    why_meaningful text,
    proxy_measure text,
    improvement_notes text,
    change_mapping varchar(30) CHECK (change_mapping IN ('New', 'Unchanged', 'Replaced', 'Removed')),
    pillar_id integer REFERENCES reference.pillar(pillar_id),
    pillar_goal_id integer REFERENCES reference.pillar_goal(pillar_goal_id),
    is_city boolean NOT NULL DEFAULT false,
    is_agency boolean NOT NULL DEFAULT false,
    is_service boolean NOT NULL DEFAULT false,
    validated boolean NOT NULL DEFAULT false,
    created_date date NOT NULL DEFAULT current_date,
    last_updated timestamptz NOT NULL DEFAULT now(),
    CHECK (is_city OR is_agency OR is_service),
    CHECK (format_type <> 'Rate' OR display_unit IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS performance.measure_actuals (
    actual_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    measure_id integer NOT NULL REFERENCES performance.performance_measure(measure_id),
    fiscal_year integer NOT NULL,
    q1_value numeric(18,4),
    q1_notes text,
    q2_value numeric(18,4),
    q2_notes text,
    q3_value numeric(18,4),
    q3_notes text,
    q4_value numeric(18,4),
    q4_notes text,
    annual_actual numeric(18,4),
    annual_actual_notes text,
    target_value numeric(18,4),
    target_value_notes text,
    reported_by integer NOT NULL REFERENCES access."user"(user_id),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (measure_id, fiscal_year)
);

CREATE TABLE IF NOT EXISTS performance.pm_goal_link (
    link_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    measure_id integer NOT NULL REFERENCES performance.performance_measure(measure_id),
    agency_goal_id integer NOT NULL REFERENCES performance.agency_goal(agency_goal_id),
    UNIQUE (measure_id, agency_goal_id)
);

CREATE TABLE IF NOT EXISTS performance.pm_service_link (
    link_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    measure_id integer NOT NULL REFERENCES performance.performance_measure(measure_id),
    service_id varchar(20) NOT NULL REFERENCES reference.service(service_id),
    UNIQUE (measure_id, service_id)
);

CREATE TABLE IF NOT EXISTS performance.pm_service_reassignment (
    reassignment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    measure_id integer NOT NULL REFERENCES performance.performance_measure(measure_id),
    old_service_id varchar(20) REFERENCES reference.service(service_id),
    new_service_id varchar(20) NOT NULL REFERENCES reference.service(service_id),
    cycle_id integer NOT NULL REFERENCES planning.plan_cycle(cycle_id),
    reason text,
    changed_date date NOT NULL DEFAULT current_date,
    changed_by integer REFERENCES access."user"(user_id)
);

CREATE TABLE IF NOT EXISTS performance.plan_service (
    plan_service_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id integer NOT NULL REFERENCES planning.agency_plan(plan_id),
    service_id varchar(20) NOT NULL REFERENCES reference.service(service_id),
    sort_order integer NOT NULL,
    UNIQUE (plan_id, service_id),
    UNIQUE (plan_id, sort_order)
);

CREATE TABLE IF NOT EXISTS performance.service_goal_link (
    sgl_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_service_id integer NOT NULL REFERENCES performance.plan_service(plan_service_id),
    agency_goal_id integer REFERENCES performance.agency_goal(agency_goal_id),
    initiative_id integer REFERENCES performance.initiative(initiative_id),
    CHECK (agency_goal_id IS NOT NULL OR initiative_id IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS performance.service_risk (
    risk_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id integer NOT NULL REFERENCES planning.agency_plan(plan_id),
    description text
);

CREATE TABLE IF NOT EXISTS performance.data_reporting (
    data_reporting_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id integer NOT NULL REFERENCES planning.agency_plan(plan_id),
    reporting_summary text,
    data_quality_notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS budget.service_fund_amount (
    sfa_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_service_id integer NOT NULL REFERENCES performance.plan_service(plan_service_id),
    fund_id varchar(20) NOT NULL CHECK (fund_id IN ('1001', 'Federal', 'State', 'Special Revenue')),
    fy_adopted numeric(18,2),
    cls_amount numeric(18,2),
    request_amount numeric(18,2),
    positions_adopted integer,
    positions_cls integer,
    positions_request integer,
    fy25_actuals numeric(18,2),
    fy26_actuals numeric(18,2),
    UNIQUE (plan_service_id, fund_id)
);

CREATE TABLE IF NOT EXISTS budget.general_fund_change (
    change_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_service_id integer NOT NULL REFERENCES performance.plan_service(plan_service_id),
    object_type varchar(100) NOT NULL CHECK (object_type IN (
        'Transfer Positions', 'Service Level Change', 'Service Realignment', 'Prior Year Spending'
    )),
    description text NOT NULL,
    dollar_change numeric(18,2),
    position_change integer,
    service_impact boolean NOT NULL DEFAULT false,
    sort_order integer NOT NULL
);

CREATE TABLE IF NOT EXISTS budget.key_spend_category (
    ksc_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_service_id integer NOT NULL REFERENCES performance.plan_service(plan_service_id),
    category varchar(50) NOT NULL CHECK (category IN ('ProfessionalServices', 'Consultants', 'NOC', 'Subcontractors')),
    amount numeric(18,2),
    description text,
    UNIQUE (plan_service_id, category)
);

CREATE TABLE IF NOT EXISTS budget.proposal_narrative (
    narrative_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_service_id integer NOT NULL UNIQUE REFERENCES performance.plan_service(plan_service_id),
    major_changes text,
    service_impact text,
    position_impact text,
    equity_narrative text,
    assumed_rates_desc text,
    grant_award_desc text
);

CREATE TABLE IF NOT EXISTS budget.cls_request (
    cls_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_service_id integer NOT NULL REFERENCES performance.plan_service(plan_service_id),
    request_name varchar(500) NOT NULL,
    request_type varchar(100),
    request_amount numeric(18,2),
    one_time boolean NOT NULL DEFAULT false,
    overall_summary text,
    justified varchar(10) CHECK (justified IN ('Yes', 'No')),
    completed boolean NOT NULL DEFAULT false,
    amount_next_fy numeric(18,2),
    amount_2next_fy numeric(18,2)
);

CREATE TABLE IF NOT EXISTS budget.cls_request_line (
    line_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cls_id integer NOT NULL REFERENCES budget.cls_request(cls_id),
    object_category varchar(200),
    amount numeric(18,2),
    justification text,
    sort_order integer NOT NULL
);

CREATE TABLE IF NOT EXISTS budget.cls_request_position (
    pos_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cls_id integer NOT NULL REFERENCES budget.cls_request(cls_id),
    classification varchar(200) NOT NULL,
    position_count integer NOT NULL CHECK (position_count > 0),
    estimated_salary numeric(18,2),
    justification text,
    explanation text
);

CREATE TABLE IF NOT EXISTS budget.enhancement (
    enhancement_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_service_id integer NOT NULL REFERENCES performance.plan_service(plan_service_id),
    name varchar(500) NOT NULL,
    description text NOT NULL,
    total_cost numeric(18,2),
    position_cost numeric(18,2),
    position_count integer,
    position_classification text,
    q1_service_delivery text,
    q2_revenue text,
    q3_cost_savings text,
    q4_future_savings text,
    external_funds boolean NOT NULL DEFAULT false,
    arpa_funded boolean NOT NULL DEFAULT false,
    completed boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS budget.enhancement_measure (
    em_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enhancement_id integer NOT NULL REFERENCES budget.enhancement(enhancement_id),
    measure_title varchar(500) NOT NULL,
    measure_type varchar(30) NOT NULL CHECK (measure_type IN ('Output', 'Efficiency', 'Effectiveness', 'Outcome')),
    baseline_value numeric(18,4),
    target_value numeric(18,4),
    data_type varchar(20) CHECK (data_type IN ('Number', 'Percentage', 'Count')),
    sort_order integer NOT NULL
);

CREATE TABLE IF NOT EXISTS budget.coa_request (
    coa_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_service_id integer NOT NULL REFERENCES performance.plan_service(plan_service_id),
    request_type varchar(100) NOT NULL CHECK (request_type IN ('New Cost Center', 'Rename', 'Move Service')),
    new_cost_center_name varchar(300),
    justification text NOT NULL,
    criteria_met jsonb,
    approval_status varchar(30) NOT NULL CHECK (approval_status IN ('Pending', 'Approved', 'Denied')),
    reviewed_by integer REFERENCES access."user"(user_id)
);

CREATE TABLE IF NOT EXISTS review.plan_review (
    review_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id integer NOT NULL REFERENCES planning.agency_plan(plan_id),
    reviewer_id integer NOT NULL REFERENCES access."user"(user_id),
    review_started_at timestamptz,
    feedback_released_at timestamptz,
    overall_score numeric(5,2),
    internal_notes text,
    review_complete boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS review.section_score (
    score_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id integer NOT NULL REFERENCES review.plan_review(review_id),
    section_code varchar(20) NOT NULL CHECK (section_code IN ('S1', 'S2', 'S3', 'S4_KPI', 'S4_Metric', 'S5', 'S6')),
    criterion_code varchar(10) NOT NULL,
    score integer CHECK (score BETWEEN 1 AND 4),
    weight numeric(5,2) NOT NULL,
    weighted_score numeric(8,4) NOT NULL,
    justification text
);

CREATE TABLE IF NOT EXISTS review.section_feedback (
    feedback_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id integer NOT NULL REFERENCES review.plan_review(review_id),
    section_code varchar(20) NOT NULL CHECK (section_code IN ('Header', 'OverviewVision', 'Goals', 'Services', 'DataReporting')),
    feedback_text text,
    return_required boolean NOT NULL DEFAULT false,
    resolved_at timestamptz
);

CREATE TABLE IF NOT EXISTS workflow.approval_record (
    approval_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id integer NOT NULL REFERENCES planning.agency_plan(plan_id),
    approver_id integer NOT NULL REFERENCES access."user"(user_id),
    approver_role varchar(30) NOT NULL CHECK (approver_role IN ('AgencyDirector', 'DeputyMayor', 'CAOffice', 'BBMRReviewer')),
    action varchar(20) NOT NULL CHECK (action IN ('Approved', 'Returned', 'Delegated')),
    notes text,
    return_target varchar(30) CHECK (return_target IN ('OPI', 'BBMR', 'Agency')),
    action_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE workflow.approval_record
    DROP CONSTRAINT IF EXISTS approval_record_approver_role_check;
ALTER TABLE workflow.approval_record
    ADD CONSTRAINT approval_record_approver_role_check
    CHECK (approver_role IN ('AgencyDirector', 'DeputyMayor', 'CAOffice', 'BBMRReviewer'));

CREATE TABLE IF NOT EXISTS workflow.plan_status_history (
    history_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id integer NOT NULL REFERENCES planning.agency_plan(plan_id),
    changed_by integer NOT NULL REFERENCES access."user"(user_id),
    from_status varchar(30) NOT NULL,
    to_status varchar(30) NOT NULL,
    plan_phase varchar(20) NOT NULL CHECK (plan_phase IN ('PerformancePlan', 'BudgetProposal')),
    changed_at timestamptz NOT NULL DEFAULT now(),
    notes text
);

CREATE TABLE IF NOT EXISTS amendment.plan_amendment (
    amendment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id integer NOT NULL REFERENCES planning.agency_plan(plan_id),
    initiated_by integer NOT NULL REFERENCES access."user"(user_id),
    reason text NOT NULL,
    amendment_status varchar(30) NOT NULL CHECK (amendment_status IN ('Open', 'AgencyEditing', 'Resubmitted', 'Reapproved')),
    initiated_at timestamptz NOT NULL DEFAULT now(),
    reapproved_at timestamptz,
    version_before integer NOT NULL,
    version_after integer
);

CREATE TABLE IF NOT EXISTS amendment.amendment_unlock (
    unlock_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amendment_id integer NOT NULL REFERENCES amendment.plan_amendment(amendment_id),
    section_code varchar(30) NOT NULL,
    unlock_reason text,
    relocked_at timestamptz
);

CREATE TABLE IF NOT EXISTS output.slide_deck_export (
    export_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id integer NOT NULL REFERENCES planning.agency_plan(plan_id),
    generated_by integer NOT NULL REFERENCES access."user"(user_id),
    generated_at timestamptz NOT NULL DEFAULT now(),
    plan_version integer NOT NULL,
    file_path varchar(500) NOT NULL,
    trigger varchar(30) NOT NULL CHECK (trigger IN ('Auto', 'Manual'))
);

CREATE TABLE IF NOT EXISTS output.notification (
    notification_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id integer REFERENCES planning.agency_plan(plan_id),
    recipient_id integer NOT NULL REFERENCES access."user"(user_id),
    notification_type varchar(50) NOT NULL CHECK (notification_type IN (
        'PlanSubmitted', 'FeedbackReturned', 'DirectorSignOffNeeded',
        'ApprovalNeeded', 'PlanApproved', 'AmendmentOpened'
    )),
    sent_at timestamptz NOT NULL DEFAULT now(),
    read_at timestamptz,
    channel varchar(20) NOT NULL CHECK (channel IN ('Email', 'InApp'))
);

CREATE INDEX IF NOT EXISTS idx_pillar_goal_pillar_id ON reference.pillar_goal(pillar_id);
CREATE INDEX IF NOT EXISTS idx_service_agency_id ON reference.service(agency_id);
CREATE INDEX IF NOT EXISTS idx_cost_center_service_id ON reference.cost_center(service_id);
CREATE INDEX IF NOT EXISTS idx_cost_center_agency_id ON reference.cost_center(agency_id);
CREATE INDEX IF NOT EXISTS idx_plan_entity_parent_agency_id ON reference.plan_entity(parent_agency_id);
CREATE INDEX IF NOT EXISTS idx_plan_entity_service_entity_id ON reference.plan_entity_service(entity_id);
CREATE INDEX IF NOT EXISTS idx_plan_entity_service_service_id ON reference.plan_entity_service(service_id);

CREATE INDEX IF NOT EXISTS idx_user_role_user_id ON access.user_role(user_id);
CREATE INDEX IF NOT EXISTS idx_user_role_app_role ON access.user_role(app_role);
CREATE INDEX IF NOT EXISTS idx_user_role_agency_id ON access.user_role(agency_id);
CREATE INDEX IF NOT EXISTS idx_user_agency_access_user_id ON access.user_agency_access(user_id);
CREATE INDEX IF NOT EXISTS idx_user_agency_access_agency_id ON access.user_agency_access(agency_id);
CREATE INDEX IF NOT EXISTS idx_user_agency_access_service_id ON access.user_agency_access(service_id);

CREATE INDEX IF NOT EXISTS idx_plan_cycle_status ON planning.plan_cycle(cycle_status);
CREATE INDEX IF NOT EXISTS idx_agency_plan_agency_id ON planning.agency_plan(agency_id);
CREATE INDEX IF NOT EXISTS idx_agency_plan_entity_id ON planning.agency_plan(entity_id);
CREATE INDEX IF NOT EXISTS idx_agency_plan_cycle_id ON planning.agency_plan(cycle_id);
CREATE INDEX IF NOT EXISTS idx_agency_plan_plan_status ON planning.agency_plan(plan_status);
CREATE INDEX IF NOT EXISTS idx_agency_plan_budget_status ON planning.agency_plan(budget_status);

CREATE INDEX IF NOT EXISTS idx_plan_header_plan_id ON performance.plan_header(plan_id);
CREATE INDEX IF NOT EXISTS idx_mission_vision_plan_id ON performance.mission_vision(plan_id);
CREATE INDEX IF NOT EXISTS idx_plan_pillar_alignment_plan_id ON performance.plan_pillar_alignment(plan_id);
CREATE INDEX IF NOT EXISTS idx_agency_goal_plan_id ON performance.agency_goal(plan_id);
CREATE INDEX IF NOT EXISTS idx_agency_goal_pillar_link_goal_id ON performance.agency_goal_pillar_link(agency_goal_id);
CREATE INDEX IF NOT EXISTS idx_agency_goal_pillar_link_pillar_goal_id ON performance.agency_goal_pillar_link(pillar_goal_id);
CREATE INDEX IF NOT EXISTS idx_initiative_status ON performance.initiative(status);
CREATE INDEX IF NOT EXISTS idx_goal_initiative_goal_id ON performance.agency_goal_initiative_link(agency_goal_id);
CREATE INDEX IF NOT EXISTS idx_goal_initiative_initiative_id ON performance.agency_goal_initiative_link(initiative_id);
CREATE INDEX IF NOT EXISTS idx_performance_measure_agency_id ON performance.performance_measure(agency_id);
CREATE INDEX IF NOT EXISTS idx_performance_measure_initial_cycle ON performance.performance_measure(initial_cycle);
CREATE INDEX IF NOT EXISTS idx_performance_measure_pillar_id ON performance.performance_measure(pillar_id);
CREATE INDEX IF NOT EXISTS idx_measure_actuals_measure_id ON performance.measure_actuals(measure_id);
CREATE INDEX IF NOT EXISTS idx_pm_goal_link_measure_id ON performance.pm_goal_link(measure_id);
CREATE INDEX IF NOT EXISTS idx_pm_goal_link_agency_goal_id ON performance.pm_goal_link(agency_goal_id);
CREATE INDEX IF NOT EXISTS idx_pm_service_link_measure_id ON performance.pm_service_link(measure_id);
CREATE INDEX IF NOT EXISTS idx_pm_service_link_service_id ON performance.pm_service_link(service_id);
CREATE INDEX IF NOT EXISTS idx_plan_service_plan_id ON performance.plan_service(plan_id);
CREATE INDEX IF NOT EXISTS idx_plan_service_service_id ON performance.plan_service(service_id);
CREATE INDEX IF NOT EXISTS idx_service_goal_link_plan_service_id ON performance.service_goal_link(plan_service_id);
CREATE INDEX IF NOT EXISTS idx_service_risk_plan_id ON performance.service_risk(plan_id);
CREATE INDEX IF NOT EXISTS idx_data_reporting_plan_id ON performance.data_reporting(plan_id);

CREATE INDEX IF NOT EXISTS idx_service_fund_amount_plan_service_id ON budget.service_fund_amount(plan_service_id);
CREATE INDEX IF NOT EXISTS idx_general_fund_change_plan_service_id ON budget.general_fund_change(plan_service_id);
CREATE INDEX IF NOT EXISTS idx_key_spend_category_plan_service_id ON budget.key_spend_category(plan_service_id);
CREATE INDEX IF NOT EXISTS idx_proposal_narrative_plan_service_id ON budget.proposal_narrative(plan_service_id);
CREATE INDEX IF NOT EXISTS idx_cls_request_plan_service_id ON budget.cls_request(plan_service_id);
CREATE INDEX IF NOT EXISTS idx_cls_request_line_cls_id ON budget.cls_request_line(cls_id);
CREATE INDEX IF NOT EXISTS idx_cls_request_position_cls_id ON budget.cls_request_position(cls_id);
CREATE INDEX IF NOT EXISTS idx_enhancement_plan_service_id ON budget.enhancement(plan_service_id);
CREATE INDEX IF NOT EXISTS idx_enhancement_measure_enhancement_id ON budget.enhancement_measure(enhancement_id);
CREATE INDEX IF NOT EXISTS idx_coa_request_plan_service_id ON budget.coa_request(plan_service_id);

CREATE INDEX IF NOT EXISTS idx_plan_review_plan_id ON review.plan_review(plan_id);
CREATE INDEX IF NOT EXISTS idx_plan_review_reviewer_id ON review.plan_review(reviewer_id);
CREATE INDEX IF NOT EXISTS idx_section_score_review_id ON review.section_score(review_id);
CREATE INDEX IF NOT EXISTS idx_section_feedback_review_id ON review.section_feedback(review_id);

CREATE INDEX IF NOT EXISTS idx_approval_record_plan_id ON workflow.approval_record(plan_id);
CREATE INDEX IF NOT EXISTS idx_approval_record_approver_id ON workflow.approval_record(approver_id);
CREATE INDEX IF NOT EXISTS idx_plan_status_history_plan_id ON workflow.plan_status_history(plan_id);
CREATE INDEX IF NOT EXISTS idx_plan_status_history_changed_by ON workflow.plan_status_history(changed_by);

CREATE INDEX IF NOT EXISTS idx_plan_amendment_plan_id ON amendment.plan_amendment(plan_id);
CREATE INDEX IF NOT EXISTS idx_amendment_unlock_amendment_id ON amendment.amendment_unlock(amendment_id);

CREATE INDEX IF NOT EXISTS idx_slide_deck_export_plan_id ON output.slide_deck_export(plan_id);
CREATE INDEX IF NOT EXISTS idx_notification_plan_id ON output.notification(plan_id);
CREATE INDEX IF NOT EXISTS idx_notification_recipient_id ON output.notification(recipient_id);

COMMIT;
